include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    library_private_types_in_public_api: false

analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    one_member_abstracts: ignore
    use_build_context_synchronously: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
