import 'package:bloc_clean_architecture/src/common/blocs/localization/bloc/localization_bloc.dart';
import 'package:bloc_clean_architecture/src/data/model/response/localization_dto.dart';
import 'package:bloc_clean_architecture/src/data/model/response/resource_dto.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'localization_key_extension.dart';

enum LocalizationKey {
  errorMessageDialogTitle(value: 'errorMessageDialogTitle', defaultValue: 'Hata'),
  forceUpdateDialogTitle(value: 'forceUpdateDialogTitle', defaultValue: 'Güncelleme Mevcut'),
  forceUpdateDialogMessage(value: 'forceUpdateDialogMessage', defaultValue: 'Uygulamanızın güncel bir sürümü mevcut. Lütfen uygulamanızı güncelleyin.'),
  fieldRequired(value: 'fieldRequired', defaultValue: 'Bu alan zorunludur.'),
  passwordMustBeAtLeastFourCharacters(value: 'passwordMustBeAtLeastFourCharacters', defaultValue: 'Şifreniz en az 4 karakter olmalıdır.'),
  passwordsDoNotMatch(value: 'passwordsDoNotMatch', defaultValue: 'Şifreler uyuşmuyor.'),
  enterValidEmail(value: 'enterValidEmail', defaultValue: 'Geçerli bir e-posta adresi giriniz.'),
  unknownErrorOccured(value: 'unknownErrorOccured', defaultValue: 'Beklenmeyen bir hata oluştu.'),
  operationSuccessful(value: 'operationSuccessful', defaultValue: 'İşlem başarılı.'),
  tryAgainLater(value: 'tryAgainLater', defaultValue: 'Lütfen daha sonra tekrar deneyin.'),
  userAgreementText(value: 'userAgreementText', defaultValue: 'Kullanıcı Sözleşmesi'),
  confidentialityAgreementText(value: 'confidentialityAgreementText', defaultValue: 'Gizlilik Sözleşmesi'),
  search(value: 'search', defaultValue: 'Ara'),
  dataNotFoundDescription(value: 'dataNotFoundDescription', defaultValue: 'Aradığınız veri bulunamadı.'),
  code(value: 'code', defaultValue: 'Kod'),
  phone(value: 'phone', defaultValue: 'Telefon'),
  contactUs(value: 'contactUs', defaultValue: 'Bize Ulaşın'),
  mailSubject(value: 'mailSubject', defaultValue: 'Mail Konusu'),
  login(value: 'login', defaultValue: 'Giriş'),
  register(value: 'register', defaultValue: 'Kayıt Ol'),
  userAgreementValidationMessage(value: 'userAgreementValidationMessage', defaultValue: 'Kullanıcı sözleşmesini kabul etmelisiniz.'),
  confidentialityAgreementValidationMessage(value: 'confidentialityAgreementValidationMessage', defaultValue: 'Gizlilik sözleşmesini kabul etmelisiniz'),
  forgotPassword(value: 'forgotPassword', defaultValue: 'Şifremi Unuttum'),
  password(value: 'password', defaultValue: 'Şifre'),
  passwordAgain(value: 'passwordAgain', defaultValue: 'Şifre Tekrarı'),
  username(value: 'username', defaultValue: 'Kullanıcı Adı'),
  deletionConfirmation(value: 'deletionConfirmation', defaultValue: 'Silme Onayı'),
  deletionConfirmationContent(value: 'deletionConfirmationContent', defaultValue: 'Bu işlem geri alınamaz. Devam etmek istediğinize emin misiniz?'),
  delete(value: 'delete', defaultValue: 'Sil'),
  giveUp(value: 'giveUp', defaultValue: 'Vazgeç'),
  phoneNumber(value: 'phoneNumber', defaultValue: 'Telefon Numarası'),
  addresses(value: 'addresses', defaultValue: 'Adresler'),
  save(value: 'save', defaultValue: 'Kaydet'),
  somethingWentWrongDescription(value: 'somethingWentWrongDescription', defaultValue: 'Bir hata oluştu. Lütfen daha sonra tekrar deneyin.'),
  date(value: 'date', defaultValue: 'Tarih'),
  thisFieldIsRequired(value: 'thisFieldIsRequired', defaultValue: 'Bu alan zorunludur.'),
  validationMustBeGreaterThanZero(value: 'validationMustBeGreaterThanZero', defaultValue: 'Bu alan sıfırdan büyük olmalıdır.'),
  description(value: 'description', defaultValue: 'Açıklama'),
  forgotPasswordExplain(value: 'forgotPasswordExplain', defaultValue: 'Şifrenizi yenilemek için kod göndereceğiz. Lütfen kayıt olduğunuz telefon numaranızı girin.'),
  next(value: 'next', defaultValue: 'İleri'),
  name(value: 'name', defaultValue: 'Adı'),
  surname(value: 'surname', defaultValue: 'Soyadı'),
  email(value: 'email', defaultValue: 'E-posta'),
  userInformations(value: 'userInformations', defaultValue: 'Kullanıcı Bilgileri'),
  settings(value: 'settings', defaultValue: 'Ayarlar'),
  themeSelection(value: 'themeSelection', defaultValue: 'Tema Seçimi'),
  darkMode(value: 'darkMode', defaultValue: 'Koyu Mod'),
  lightMode(value: 'lightMode', defaultValue: 'Açık Mod'),
  cultureSelection(value: 'cultureSelection', defaultValue: 'Dil Seçimi'),
  updatePassword(value: 'updatePassword', defaultValue: 'Şifre Güncelle'),
  updatePasswordDescription1(value: 'updatePasswordDescription1', defaultValue: 'Doğrulamak için mevcut şifrenizi giriniz.'),
  updatePasswordDescription2(value: 'updatePasswordDescription2', defaultValue: 'Lütfen "yeni şifre" ve "tekrar" alanlarını doldurunuz.'),
  currentPassword(value: 'currentPassword', defaultValue: 'Mevcut Şifre'),
  pleaseCheckYourNetworkConnection(value: 'pleaseCheckYourNetworkConnection', defaultValue: 'Lütfen internet bağlantınızı kontrol ediniz.'),
  dataNotFoundToDisplay(value: 'dataNotFoundToDisplay', defaultValue: 'Listelenecek veri bulunamadı.'),
  verification(value: 'verification', defaultValue: 'Doğrulama'),
  enterCodeSentToNumber(value: 'enterCodeSentToNumber', defaultValue: 'Numaranıza gönderilen kodu giriniz.'),
  didNotReceiveCode(value: 'didNotReceiveCode', defaultValue: 'Kod gelmedi mi?'),
  resend(value: 'resend', defaultValue: 'Tekrar Gönder'),
  phoneCallError(value: 'phoneCallError', defaultValue: 'Telefon araması yapılırken bir hata oluştu.'),
  securityCodeMustBeAtLeastSixCharacters(value: 'securityCodeMustBeAtLeastSixCharacters', defaultValue: 'Doğrulama kodu en az 6 karakter olmalıdır.'),
  securityCode(value: 'securityCode', defaultValue: 'Doğrulama Kodu'),
  validationMustBeLessThanOneHundredMillion(value: 'validationMustBeLessThanOneHundredMillion', defaultValue: "Bu alan 100.000.000'den küçük olmalıdır."),
  adminOperations(value: 'adminOperations', defaultValue: 'Admin İşlemleri'),
  ok(value: 'ok', defaultValue: 'Tamam'),
  cancel(value: 'cancel', defaultValue: 'İptal'),
  signOut(value: 'signOut', defaultValue: 'Çıkış Yap'),
  hello(value: 'hello', defaultValue: 'Merhaba'),
  mailBody(value: 'mailBody', defaultValue: 'Şikayetiniz ya da öneriniz varsa aşağıya mesajınızı yazabilirsiniz.'),
  phoneInformations(value: 'phoneInformations', defaultValue: 'Telefon Bilgileri'),
  accept(value: 'accept', defaultValue: 'Kabul Et'),
  yes(value: 'yes', defaultValue: 'Evet'),
  no(value: 'no', defaultValue: 'Hayır'),
  cleanArchitecture(value: 'cleanArchitecture', defaultValue: 'Clean Architecture'),
  menuTitle(value: 'menuTitle', defaultValue: 'Menü Başlığı'),
  myAccount(value: 'myAccount', defaultValue: 'Hesabım'),
  logout(value: 'logout', defaultValue: 'Çıkış Yap'),
  logoutConfirmation(value: 'logoutConfirmation', defaultValue: 'Çıkış Yapmak istediğinize emin misiniz?'),
  version(value: 'version', defaultValue: 'Sürüm'),
  cart(value: 'cart', defaultValue: 'Sepet'),
  goToProducts(value: 'goToProducts', defaultValue: 'Ürünlere Git'),
  deleteConfirmation(value: 'deleteConfirmation', defaultValue: 'Silme Onayı'),
  deleteConfirmationMessage(value: 'deleteConfirmationMessage', defaultValue: 'Bu işlem geri alınamaz. Devam etmek istediğinize emin misiniz?'),
  amountToBePaid(value: 'amountToBePaid', defaultValue: 'Ödenecek Tutar'),
  continuee(value: 'continuee', defaultValue: 'Devam Et'),
  products(value: 'products', defaultValue: 'Ürünler'),
  searchForFlavors(value: 'searchForFlavors', defaultValue: 'Lezzetleri Ara'),
  noDataToDisplay(value: 'noDataToDisplay', defaultValue: 'Gösterilecek veri bulunamadı'),
  dataNotFound(value: 'dataNotFound', defaultValue: 'Veri Bulunamadı'),
  orders(value: 'orders', defaultValue: 'Siparişler'),
  all(value: 'all', defaultValue: 'Tümü'),
  deleteAll(value: 'deleteAll', defaultValue: 'Tümünü Sil'),
  yourCartIsEmpty(value: 'yourCartIsEmpty', defaultValue: 'Sepetiniz Boş'),
  order(value: 'order', defaultValue: 'Sipariş'),
  selectAddress(value: 'selectAddress', defaultValue: 'Adres Seçiniz'),
  edit(value: 'edit', defaultValue: 'Düzenle'),
  addNew(value: 'addNew', defaultValue: 'Yeni Ekle'),
  addAddress(value: 'addAddress', defaultValue: 'Adres Ekle'),
  paymentMethod(value: 'paymentMethod', defaultValue: 'Ödeme Yöntemi'),
  cashOnDelivery(value: 'cashOnDelivery', defaultValue: 'Kapıda Nakit Ödeme'),
  creditCardOnDelivery(value: 'creditCardOnDelivery', defaultValue: 'Kapıda Kredi Kartı ile Ödeme'),
  orderNoteTitle(value: 'orderNoteTitle', defaultValue: 'Sipariş Notu'),
  orderNoteHintText(value: 'orderNoteHintText', defaultValue: 'Sipariş notunuzu buraya yazabilirsiniz.'),
  sendTheOrder(value: 'sendTheOrder', defaultValue: 'Siparişi Gönder'),
  noAddressFound(value: 'noAddressFound', defaultValue: 'Adres Bulunamadı'),
  newAddress(value: 'newAddress', defaultValue: 'Yeni Adres'),
  editAddress(value: 'editAddress', defaultValue: 'Adres Düzenle'),
  addressName(value: 'addressName', defaultValue: 'Adres Adı'),
  cityName(value: 'cityName', defaultValue: 'Şehir Adı'),
  districtName(value: 'districtName', defaultValue: 'İlçe Adı'),
  addressDescription(value: 'addressDescription', defaultValue: 'Adres Açıklaması'),
  addNewAddress(value: 'addNewAddress', defaultValue: 'Yeni Adres Ekle'),
  orderDetails(value: 'orderDetails', defaultValue: 'Sipariş Detayları'),
  orderNumber(value: 'orderNumber', defaultValue: 'Sipariş Numarası'),
  delivered(value: 'delivered', defaultValue: 'Teslim Edildi'),
  pending(value: 'pending', defaultValue: 'Beklemede'),
  preparing(value: 'preparing', defaultValue: 'Hazırlanıyor'),
  cancelled(value: 'cancelled', defaultValue: 'İptal Edildi'),
  orderDate(value: 'orderDate', defaultValue: 'Sipariş Tarihi'),
  address(value: 'address', defaultValue: 'Adres'),
  totalAmount(value: 'totalAmount', defaultValue: 'Toplam Tutar'),
  cancelButtonConfirmation(value: 'cancelButtonConfirmation', defaultValue: 'Siparişi iptal etmek istediğinize emin misiniz?'),
  orderNote(value: 'orderNote', defaultValue: 'Sipariş Notu'),
  orderNotFoundToDisplay(value: 'orderNotFoundToDisplay', defaultValue: 'Sipariş bulunamadı.'),
  categories(value: 'categories', defaultValue: 'Kategoriler'),
  orderStatusPending(value: 'orderStatusPending', defaultValue: 'Beklemede'),
  orderStatusPreparing(value: 'orderStatusPreparing', defaultValue: 'Hazırlanıyor'),
  orderStatusCancelled(value: 'orderStatusCancelled', defaultValue: 'İptal Edildi'),
  orderStatusDelivered(value: 'orderStatusDelivered', defaultValue: 'Teslim Edildi'),
  orderStatus(value: 'orderStatus', defaultValue: 'Sipariş Durumu'),
  noCategoryFound(value: 'noCategoryFound', defaultValue: 'Kategori Bulunamadı'),
  addCategory(value: 'addCategory', defaultValue: 'Kategori Ekle'),
  editCategory(value: 'editCategory', defaultValue: 'Kategori Düzenle'),
  categoryName(value: 'categoryName', defaultValue: 'Kategori Adı'),
  newCategory(value: 'newCategory', defaultValue: 'Yeni Kategori'),
  productDetail(value: 'productDetail', defaultValue: 'Ürün Detayı'),
  newProduct(value: 'newProduct', defaultValue: 'Yeni Ürün'),
  editProduct(value: 'editProduct', defaultValue: 'Ürün Düzenle'),
  createProduct(value: 'createProduct', defaultValue: 'Ürün Oluştur'),
  infoMessageDialogTitle(value: 'infoMessageDialogTitle', defaultValue: 'Bilgilendirme'),
  productImageRequired(value: 'productImageRequired', defaultValue: 'Ürün resmi gereklidir'),
  productName(value: 'productName', defaultValue: 'Ürün Adı'),
  productDescription(value: 'productDescription', defaultValue: 'Ürün Açıklaması'),
  price(value: 'price', defaultValue: 'Fiyat'),
  selectCategory(value: 'selectCategory', defaultValue: 'Kategori Seçiniz'),
  ;

  const LocalizationKey({required this.value, required this.defaultValue});

  final String value;
  final String defaultValue;
}
